### ISSUE TITLE
Support for zero 11x?

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [Koxx3/SmartController_SmartDisplay_ESP32#25]
Hello,
I'm considering donating this project to aim in fine-tuning or replacing QS-S4 used in Zero 11x, especially quite aggressive start in 1st-eco-single mode. Also, it's very hard to get steady speed around 15-20km/h.

Is this project compatible with hardware available in this scooter?

**Comment by Koxx3** [comment]
hello,
if the 11x is using qss4 with 'protocol 4' mode, yes, it should work fine 😁
i only tried with a 10x 😉
