### ISSUE TITLE
Working with 2.8 320x240 LCD 

### ISSUE THREAD

**Issue by xromansx** [Koxx3/SmartController_SmartDisplay_ESP32#30]
I would like to use it with RM68090 LCD would like to know if it's adapted for 320x240 resolution ? as I understood originally it was done for 2.4 display ?

**Comment by Koxx3** [comment]
hello !
it might be a bit tricky since the display controller of this tft panel is not supported by tft_espi library.
i advise you to select a screen with a compatible library controller and spi interface. it will be easier. bit, if you have time, everything is possible 😉

**Comment by xromansx** [comment]
I saw that there is already opened ticket for RM68090 in tft_espi library so I don't think it would be hard to make it working with this library.What about resolution 320x240 should be fine ?

**Comment by Koxx3** [comment]
yes, it already supports the 320x240 resolution 😉
