### ISSUE TITLE
Hello, can this be used on the motherboard of the balance car?

### ISSUE THREAD

**Issue by mouixong** [Koxx3/SmartController_SmartDisplay_ESP32#32]
Is there a firmware or tutorial for this? I can't find it on Youtube.

**Comment by Koxx3** [comment]
Hello, 
it depends on which controller the balance car is based. 
If it VESC, then yes.
If it another controller with open source, with adaptations, yes, it can work too.

**Comment by mouixong** [comment]
https://github.com/larsmm/hoverboard-firmware-hack-FOC-bbcar

**Comment by mouixong** [comment]
> https://github.com/larsmm/hoverboard-firmware-hack-FOC-bbcar
The motherboard of my balance car is using this firmware now

**Comment by Koxx3** [comment]
currently not compatible with this firmware.
