### ISSUE TITLE
Which firmware is more update, SmartESC_STM32_v3 or SmartESC_STM32_v2?

### ISSUE THREAD

**Issue by casainho** [Koxx3/SmartController_SmartDisplay_ESP32#34]
Hi.

I would like to run OpenSource firmware on my M365. I really like the original firmware from Stancecoke as I collaborated with him on the Kuteng EBike motor controller OpenSource firmware and I developed the one for TSDZ2 EBike mid drive motor firmware.

Congratulations on this project and to everyone who worked on this (all the authors of the other forks!).

Should I focus on SmartESC_STM32_v3?? or SmartESC_STM32_v2??

I wish to learn and have a tool / code to have FOC on other boards with different microcontroller.

**Comment by Koxx3** [comment]
Hello,
SmartESC_STM32_v1 is based on open source Hoverboard code. It works but the code is messy and the FOC code is generated with Mathlab Simulink (hard to maintain).
SmartESC_STM32_v2 is based on ST Microelectronics FOC library. It works but it is difficult to configure.
SmartESC_STM32_v3 is based on EBiCS Firmware. It works but has some problem at low speed start.

**Comment by casainho** [comment]
Ok, I will focus on V3 from Stancecoke firmware. He says there are some improvements he did recently that are not on your firmware.

When you say it works, you mean it works if I connect the display?

I understand it ignores the BMS.

Do you know what is the microcontroller on the display? I would say it is a NRF52 since it is very popular Bluetooth microcontroller and used on the popular SW102 cheap chinese ebike display, that we developed our OpenSource firmware for it.
Maybe we could develop the firmware for the display and adapt an already existing mobile app??
