### ISSUE TITLE
Do you sell PCB?

### ISSUE THREAD

**Issue by McKaNaN** [Koxx3/SmartController_SmartDisplay_ESP32#7]
I am interested in PCB but I don't have the means to do it. Do you sell it?

**Comment by Foujiwara** [comment]
Hi, you can make by yourself with Jlcpcb, the files for make it is in the project, but you should wait the last version

**Comment by Koxx3** [comment]
currently, no. I'll see later if I can sell "kits" (ready to solder) or fully prepared boards. ;)
