### ISSUE TITLE
[BUG] Script burn Efuse

### ISSUE THREAD

**Issue by jojolll** [Koxx3/SmartController_SmartDisplay_ESP32#8]
Le script ne tourne pas sur toutes les machines. Voici l'erreur constatée sur la mienne : 

`espefuse.py -p %1 --do-not-confirm set_flash_voltage 3.3V`
'espefuse.py' n’est pas reconnu en tant que commande interne

même résultat ici : 
`espefuse.exe -p %1 --do-not-confirm set_flash_voltage 3.3V`
'espefuse.exe' n’est pas reconnu en tant que commande interne

Pour pallier ce problème, j'ai exécuté cette ligne de commande, permettant à python de trouver ses modules 👍  : 
`python -m espefuse -p COM7 --do-not-confirm set_flash_voltage 3.3V`

@technoo10201 a suggéré la mise en place d'un VENV pour ne pas encombrer le système des utilisateurs avec les installations de module system wide

**Comment by Koxx3** [comment]
fixed.
https://github.com/Koxx3/SmartController_SmartDisplay_ESP32/commit/dc59bcca50811d84ac9a88c8768a6e4a50f3d48c

pour les VENV, je sais pas faire par contre :(

**Comment by Koxx3** [comment]
marked as fixed
