### ISSUE TITLE
[BUG POTENTIEL] Utilisation systématique de "Electric brake min value"

### ISSUE THREAD

**Issue by jojolll** [Koxx3/SmartController_SmartDisplay_ESP32#9]
Problème rencontré lorsque le frein n'est pas relié au smartController mais directement au contrôleur MiMo.

Même lorsque le freinage progressif est désactivé via l'application, le paramètre "Electric brake min value" est constamment envoyé dans les trames vers le contrôleur, en lieu et place du paramètre brake du Dashboard de l'application.

Vidéo descriptive  : https://youtu.be/WRUe_t0LONo

Même résultat lors de l'activation du param "Electric brake disabled on high battery", qui est tout bonnement ignoré :
![image](https://user-images.githubusercontent.com/26553241/104827624-09d52380-5860-11eb-9414-6f4fd3343799.png)
Ici on s'attendrait à avoir 0 sur le paramètre PA envoyé au controleur, mais il reçoit toujours la valeur "Electric brake min value", que j'avais réglé sur 5.

**Comment by Koxx3** [comment]
possible fix : https://github.com/Koxx3/SmartController_SmartDisplay_ESP32/commit/9be7ab8f7967c0367e73fb84a8a4bfc1464c90b2

to be tested ...

**Comment by Koxx3** [comment]
should be fixed with a0c9f9fc19e191666dd8579a4ee6d1f4a770f8f1

**Comment by Koxx3** [comment]
seems fixed ;)
